### ISSUE TITLE
six (6) attempts to get YAML (**NOT** JSON) APIs to display in redocly developer portal. 

### ISSUE THREAD

**Issue by WaterSibilantFalling** [Redocly/developer-portal-starter#114]
These APIs are YAML **NOT** JSON. These YAML API path and schema fragments were created by redocly's `create-openapi-repo` tool

As instructed by Redocly, these fragments are place in directories under the openapi directory:

```
developer-portal
      openapi
             schema
              paths
                   Abcdefg
                    Banana
                    Frog
```

## Attempt 1

The .....page.yaml file in the openapi/ dir
path   files, like v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml in the 
	 openapi/path/Abcdefg/  directory

in sidebar.yaml

```
  - group: MOA APIs
    expanded: true
    pages:
      - group: Abcdefg
        expanded: true
        pages:
          - page: "moa_Abcdefg.page.yaml/*"
```

#### Error

No "Error" messages, but didn't work 

## Attempt 2:  The same, but with each of 

```
	- page: "openapi/moa_Abcdefg.page.yaml"
	- page: "openapi/moa_Abcdefg.page.yaml/*"
	- page: "openapi/moa_Abcdefg.page.yaml/"
	- page: openapi/moa_Abcdefg.page.yaml
	- page: openapi/moa_Abcdefg.page.yaml/
	- page: openapi/moa_Abcdefg.page.yaml/*
```

Of course, none of these worked. 

Note that the last of these, which DEFINITELY does not exist, does not give an error.
Those that DO exist, DO give errors

Errors about "File not found" only appear for files that EXIST. 
When a file does NOT exist, no error. 

## Attempt 3

Directly listed each API file. 
  

```
    pages:
      - group: Abcdefg
        expanded: true
        pages:
          - page: "openapi/paths/Abcdefg/moa_Abcdefg.page.yaml"
          - page: "openapi/paths/Abcdefg/v1@Abcdefg({key})@Products@$ref.yaml"
          - page: "openapi/paths/Abcdefg/v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml"
          - page: "openapi/paths/Abcdefg/v1@Abcdefg({key})@SubCategories@$ref.yaml"
          - page: "openapi/paths/Abcdefg/v1@Abcdefg({key})@SubCategories({relatedKey}) @$ref.yaml"
          - page: "openapi/paths/Abcdefg/v1@Abcdefg({key}).yaml"
          - page: "openapi/paths/Abcdefg/v1@Abcdefg.yaml"

```

#### errors

Lots of (incorrect) errors about "could not find page"

```
Page "openapi/paths/Abcdefg/moa_Abcdefg.page.yaml" is not found. Verify path in "sidebars.yaml"

 ERROR
Could not find page: openapi/paths/Abcdefg/v1@Abcdefg({key})@Products@$ref.yaml.

 ERROR
Could not find page: openapi/paths/Abcdefg/v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml.
```

## Attempt 4

Based on the openapi directory. Not suprised that this didn't work - after all, nothing worked - but for completeness

```
  - group: MOA APIs
    expanded: true
    pages:
      - group: Abcdefg
        expanded: true
        pages:
          - page: "paths/Abcdefg/moa_Abcdefg.page.yaml"
          - page: "paths/Abcdefg/v1@Abcdefg({key})@Products@$ref.yaml"
          - page: "paths/Abcdefg/v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml"
          - page: "paths/Abcdefg/v1@Abcdefg({key})@SubCategories@$ref.yaml"
          - page: "paths/Abcdefg/v1@Abcdefg({key})@SubCategories({relatedKey})@$ref.yaml"
          - page: "paths/Abcdefg/v1@Abcdefg({key}).yaml"
          - page: "paths/Abcdefg/v1@Abcdefg.yaml"
```

#### error

```

 ERROR
Page "paths/Abcdefg/moa_Abcdefg.page.yaml" is not found. Verify path in "sidebars.yaml"

 ERROR
Could not find page: paths/Abcdefg/v1@Abcdefg({key})@Products@$ref.yaml.

 ERROR
Could not find page: paths/Abcdefg/v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml.

 ERROR
Could not find page: paths/Abcdefg/v1@Abcdefg({key})@SubCategories@$ref.yaml.

```

## Attempt 5

Put the .....page.yaml file in the same directory as the 'path' files that describe the API. This is like the APIs represented in monolithic JSON (in the openapi dir) being in the same dir as the API path file. 

```
  - group: MOA APIs
    expanded: true
    pages:
      - group: Abcdefg
        expanded: true
        pages:
          - page: "openapi/paths/Abcdefg/moa_Abcdefg.page.yaml/*"

```

error:   No error, but no APIs displayed

## Attempt 6

Put the path files in the opeanapi directory, like the JSON api file (that actually works).

```
      - group: Abcdefg
        expanded: true
        pages:
          - page: "moa_Abcdefg.page.yaml/*"
          - page: "v1@Abcdefg({key})@Products@$ref.yaml"
          - page: "v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml"
          - page: "v1@Abcdefg({key})@SubCategories@$ref.yaml"
          - page: "v1@Abcdefg({key})@SubCategories({relatedKey})@$ref.yaml"
          - page: "v1@Abcdefg({key}).yaml"
          - page: "v1@Abcdefg.yaml"
````

#### Errors

Incorrect error messages saying "Could not find page". 

```
 ERROR
Could not find page: v1@Abcdefg({key})@Products@$ref.yaml.

 ERROR
Could not find page: v1@Abcdefg({key})@Products({relatedKey})@$ref.yaml.

 ERROR
Could not find page: v1@Abcdefg({key})@SubCategories@$ref.yaml.

```

**Comment by adamaltman** [comment]
Hi @WaterSibilantFalling can you please share your `siteConfig.yaml` contents, and the contents of one of your `moa_Abcdefg.page.yaml` file?

**Comment by WaterSibilantFalling** [comment]
I think they're both default, as supplied.

#### `siteConfig.yaml`

```
meta:
  title: Plexure API Portal
  description: The one-stop-shop for Plexure API documentation
  siteUrl: https://portal-demo.redoc.ly
logo: ./images/logo.png
enableToc: true
oasDefinitions:
  userAuthorization: ./openapi/user-authorization.json
  anotherApi: ./openapi/another-api.json
  moaapis: ./openapi/moa_openapi.json
  # MUST be relative paths
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
#ga:
  # you can use any options here from https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
  # note that GA doesn't work in DEV
#  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: Plexure Repos
    icon: ./images/redocly-icon-white.png
    href: https://dev.azure.com/vmob/New%20Plexure/_git/vmob-backend/

  - search: true

footer:
  copyrightText: Copyright © Redocly 2019-2020. All right reserved.

```

#### `moa_Abcdef.page.yaml` file

```
type: reference-docs
definitionId: moaapis
showInfo: false
expand: true
label: Test Label in openapi.page.yaml
settings:
  corsProxyUrl: 'https://cors.redoc.ly' # todo use proper proxying instead of this hackaround
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: JavaScript
      - lang: Node.js


```
