### ISSUE TITLE
OpenApiTryIt component shows "Incorrect definitionId" error

### ISSUE THREAD

**Issue by timothymcmackin** [Redocly/developer-portal-starter#195]
I forked this starter and tried to use the OpenApiTryIt MDX component as described in these docs:
https://redocly.com/docs/developer-portal/guides/step-by-step/

I added the catFacts API in the `siteConfig.yaml` file:
```
oasDefinitions:
  catFacts: https://catfact.ninja/docs/api-docs.json
```

Then I created this page in a file named `developer-portal/openapi-try-it.mdx`:
```
import { OpenApiTryIt, Alert, ExplainStep, scrollToHeading } from '@redocly/developer-portal/ui';

# Testing the openapi try it component

<OpenApiTryIt
  definitionId="catFacts"
  operationId="getRandomFact"
  id="step-1"
  onResponse={({ response }) => {
    console.log(response);
  }}
/>
```

When I run the portal locally and go to http://localhost:3000/developer-portal/openapi-try-it/ , I see an error that says `Incorrect definitionId: "catFacts"`. What am I doing wrong? I've also tried downloading the openapi file and linking to it locally instead of putting the link in `oasDefinitions`.

Here's my minimal reproduction:
https://github.com/timothymcmackin/redocly-openapi-try-it

**Comment by nalesnichok** [comment]
Hi @timothymcmackin,

Thank you for contacting us.

You need to integrate the Reference docs into the Developer portal in order for the `OpenApiTryIt` component to work as expected:

https://redocly.com/docs/developer-portal/guides/reference-docs-integration/#step-2-add-pages-that-reference-the-definitions

1. Create a file `catfacts.page.yaml` (for example) in your Developer portal with the following content:

```
type: reference-docs
definitionId: catFacts
settings:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: JavaScript
      - lang: Node.js
```
3. Run `yarn clean`
4. Run `yarn start`

Let us know whether it resolved your problem.

**Comment by timothymcmackin** [comment]
Another note for people in the future who may find this item: One issue I had was that if the openapi file was missing something or had a problem, the dev portal wouldn't load and didn't seem to give me an error So if you're having this problem, make sure that your openapi file has all of the necessary things like a `servers` object.

**Comment by bjonesy** [comment]
I'm running into a similar issue but with the `OpenApiCodeSample` component.

This is my reference file:
```
type: reference-docs
versions:
  - definitionId: betterCloudApi
    id: v1
    title: BetterCloud API V1
    isDefault: false
  - definitionId: betterCloudApiv2
    id: v2
    title: BetterCloud API V2
    isDefault: true
settings:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: JavaScript
      - lang: Java
      - lang: Go
```

siteConfig
```
oasDefinitions:
  betterCloudApi: ./openapi/bettercloud-api.yaml
  betterCloudApiv2: ./openapi/bettercloud-api-v2.yaml
```

Custom mdx page
```
	<OpenApiCodeSample
	definitionId="betterCloudApi"
	operationId="get_v1_tokens_lookup"
	defaultLanguage="Java"
        />
```

I have run yarn clean multiple times and I still see this error. 
![Screen Shot 2022-04-25 at 10 56 09 AM](https://user-images.githubusercontent.com/4111688/165116259-01852965-4d25-4078-91cd-d1138b6615b1.png)

I am using the reference.page.yaml to build out pages for the spec without any issues. Only when trying to use the components and reference the definitonId do I see this issue.

```
- group: API Reference
  expanded: true
  pages:
    - page: openapi/reference.page.yaml/* // works fine with no issues
```
